baseURL = "https://photoencryption.org/"
languageCode = "en-us"
title = "Thumbnail Preserving Encryption"

theme = "introduction"
publishDir = "../docs"

[params]
    [params.home]
        introHeight              = "small"                 # Input either "medium" or "large" or "fullheight"
